pimcore:
    objects:
        class_definitions:
            data:
                map:
                    entryTypeSelect: WidgetBundle\CoreExtension\EntryTypeSelect

parameters:
    image_thumbnails:
        content_image: 'contentImage'
        gallery_image: 'galleryImage'

widget:
    list:
        sort_by: 'date'
        sort_by_store:
            date: 'news.sort_by.date'
            name: 'news.sort_by.name'
        order_by: 'desc'
        time_range: 'all'
        max_items: 0
        paginate:
            items_per_page: 10
        layouts:
            default: 'list'
            items:
                list:
                    name: 'news.list'
                latest:
                    name: 'news.latest'
    detail: ~
    entry_types:
        default: 'widget'
        items:
            news:
                name: 'news.entry_type.news'
                route: 'news_detail'
                custom_layout_id: 0