services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # INSTALLER
    #

    WerStreamtEs\WidgetPimcoreBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('WidgetPimcoreBundle')"

