services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    WidgetBundle\Document\Areabrick\News\News:
        tags:
            - { name: pimcore.area.brick, id: news }