services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WidgetBundle\Generator\LinkGeneratorInterface: '@WidgetBundle\Generator\LinkGenerator'
    WidgetBundle\Generator\LinkGenerator: ~

    WidgetBundle\Generator\RelatedEntriesGeneratorInterface: '@WidgetBundle\Generator\RelatedEntriesGenerator'
    WidgetBundle\Generator\RelatedEntriesGenerator: ~

    WidgetBundle\Generator\HeadMetaGeneratorInterface: '@WidgetBundle\Generator\HeadMetaGenerator'
    WidgetBundle\Generator\HeadMetaGenerator: ~
