services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    WidgetBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('WidgetBundle')"
        calls:
            - [setTokenStorageUserResolver, ['@Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver']]
            - [setSerializer, ['@serializer']]

    WidgetBundle\Configuration\Configuration: ~

    WidgetBundle\Controller\Admin\SettingsController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']