services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WidgetBundle\Twig\Extension\WidgetExtension:
        arguments:
            $imageThumbnails: '%image_thumbnails%'
        tags:
            - { name: twig.extension }

    WidgetBundle\Twig\Extension\RelatedEntriesExtension:
        tags:
            - { name: twig.extension }

    WidgetBundle\Twig\Extension\VideoTagExtension:
        tags:
            - { name: twig.extension }